### PR TITLE
Add and configure robots and sitemap.

### PR DESCRIPTION
**Pull request by markpbaggett**
## What Does This Do

Adds a robots file and a sitemap for RFTA.

## Why is this important

Currently, RFTA scores a 100 in SEO in Lighthouse, but you can't find anything in Google.  I believe this is due to:

1. The lack of a robots file.
2. The lack of a sitemap telling search engines what to index.

## How Can I Test?

Spin up locally or use the deploy preview branch below:

1. Path to robots:  [base-url]/robots.txt
2. Path to sitemap: [base-url]/sitemap/sitemap-index.xml

## So when will things start showing up in Google

1. When this is live and we have submitted the sitemap to Google Search Console.

### CODE REVIEW

**Comment by CanOfBees** [comment]
@markpbaggett apologies for the silly question, but I'm having a hard time getting a sitemap-index.xml with your instructions for the deploy preview. Should the URL  [deploy-preview]/sitemap/sitemap-index.xml resolve, or would it not exist in the preview?

**Comment by markpbaggett** [comment]
> @markpbaggett apologies for the silly question, but I'm having a hard time getting a sitemap-index.xml with your instructions for the deploy preview. Should the URL [deploy-preview]/sitemap/sitemap-index.xml resolve, or would it not exist in the preview?

https://deploy-preview-36--iiif-canopy.netlify.app/sitemap/sitemap-index.xml

**Comment by CanOfBees** [comment]
@markpbaggett 
> https://deploy-preview-36--iiif-canopy.netlify.app/sitemap/sitemap-index.xml
> 
> Does that not resolve for you?
It does now. Apologies, I must have been doing something wrong.

**Review by CanOfBees — APPROVED** [review]
@markpbaggett thanks for answering my question; this looks good to me.

- [x] robots.txt is available
- [x] sitemap/sitemap-index.xml is available

**Pull request merged**
